# Generated by Django 3.1.7 on 2021-04-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Dakar', max_length=235),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Senegal', max_length=235),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Other', 'Other')], default='Mr', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default='Yoff', max_length=235),
        ),
    ]
