# Generated by Django 3.1.7 on 2021-04-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210407_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='gender',
        ),
    ]
