# Generated by Django 3.1.7 on 2021-04-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210407_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='uname',
        ),
    ]
