# Generated by Django 3.1.7 on 2021-04-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verify',
            new_name='is_verified',
        ),
    ]
