# Generated by Django 3.1.7 on 2021-04-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210416_1601'),
        ('user', '0008_auto_20210421_0829'),
    ]

    operations = [
    ]
